config/routes.rb
DaBvRails::Application.routes.draw do

  # Stripe Callbacks
  mount StripeEvent::Engine => '/stripe-sentry'

  # Active Admin Routes
  ActiveAdmin.routes(self)

  # Subdomains
  constraints(Subdomain) do
    get "/" => "subdomains#index", as: 'subdomain_home'
    scope module: "subdomains" do

      # Community
      get "/disabled" => "communities#disabled", as: "community_disabled"
      get "/community_settings" => "communities#edit", as: "edit_community_settings"
      put "/community_settings" => "communities#update", as: "update_community_settings"
      get "/clear_action_items" => "communities#clear_action_items", as: "clear_action_items"
      get "/activities" => "communities#activities", as: "community_activities"
      get "/autocomplete-members" => "communities#autocomplete_members", as: "autocomplete_members"

      # Roles and Permissions
      get '/roles/user_profile/:user_profile_id/edit' => 'roles#user_profile', as: "user_profile_roles"
      put '/roles/:id/user_profile/:user_profile_id' => 'roles#update_user_profile', as: "user_profile_role"
      delete '/roles/:id/user_profile/:user_profile_id' => 'roles#delete_user_profile', as: "user_profile_role"
      resources :roles, except: [:show]

      # Roster assignments
      get '/roster_assignments/pending' => 'roster_assignments#pending', as: "pending_roster_assignments"
      get '/my_roster_assignments' => 'roster_assignments#mine', as: "my_roster_assignments"
      put '/roster_assignments/batch_approve' => "roster_assignments#batch_approve", as: "batch_approve_roster_assignments"
      put '/roster_assignments/batch_reject' => "roster_assignments#batch_reject", as: "batch_reject_roster_assignments"
      delete '/roster_assignments/batch_remove' => "roster_assignments#batch_destroy", as: "batch_destroy_roster_assignments"
      resources :roster_assignments, except: [:show, :new, :edit, :update] do
        member do
          put :approve
          put :reject
        end
        collection do
          get 'game/:id' => 'roster_assignments#game', as: :game
        end
      end

      # Community profiles
      resources :community_profiles, only: [:destroy]

      # Community applications
      resources :community_applications, except: [:edit, :update] do
        member do
          post :accept
          post :reject
        end
      end

      # Custom Forms
      resources :custom_forms, except: :show do
        resources :submissions, shallow: true, only: [:index, :destroy]
        resources :submissions, except: [:update, :edit, :destroy]
        member do
          put :publish
          put :unpublish
        end
      end
      get "/custom_forms/:id/thankyou" => 'custom_forms#thankyou', as: :custom_form_thankyou

      # Discussions
      resources :comments, except: [:index, :show] do
        member do
          post :lock
          post :unlock
        end
      end
      resources :discussion_spaces do
        resources :discussions, except: [:index], shallow: true do
          member do
            post :lock
            post :unlock
          end
        end
      end

      # Announcements
      resources :announcements, except: [:edit, :update] do
        member do
          post :lock
          post :unlock
        end
        collection do
          get :community
          get 'game/:id' => 'announcements#game', as: :game
          delete 'batch_destroy' => "announcements#batch_destroy", as: "batch_destroy"
        end
      end

      # Pages
      resources :page_spaces do
        resources :pages, shallow: true, except: [:index]
      end

      # Community Games
      resources :community_games, except: [:show] do
        collection do
          get :autocomplete
        end
      end

      # Minecraft
      get 'minecraft/whitelist' => 'minecraft#whitelist', as: 'minecraft_whitelist'

      # Events
      resources :events do
        member do
          get :invites
        end
        collection do
          get :past
        end
      end
      get '/events/:year/:month' => 'events#month_index', as: "month_events"
      get '/events/:year/week/:week' => 'events#week_index', as: "week_events"

      # Invites
      put 'invites/batch_update' => "invites#batch_update", as: "invites_batch_update"
      resources :invites, only: [:edit, :update]

      resources :community_invites, only: [:index]
      post "/community_invites/mass_create" => "community_invites#mass_create"
      get "/community_invites/autocomplete" => "community_invites#autocomplete"
    end

  end # End of "constraints(Subdomain)" block

  # Routes that use no subdomain
  defaults subdomain: false do

    # Admin Users
    devise_for :admin_users, path: ActiveAdmin.application.default_namespace,
                             controllers: {sessions: 'alexandria/devise/sessions', passwords: 'alexandria/devise/passwords'},
                             path_names: { sign_in: 'login', sign_out: "logout" }
    devise_scope :admin_user do
      get "/alexandria/login" => "alexandria/devise/sessions#new"
      post "/alexandria/login" => "alexandria/devise/sessions#create"
      get "/alexandria/logout" => "alexandria/devise/sessions#destroy"
      get "/admin_users/sign_in" => "alexandria/devise/sessions#new"
      post "/admin_users/sign_in" => "alexandria/devise/sessions#create"
      get "/admin_users/password/edit" => "alexandria/devise/passwords#edit"
      put "/admin_users/password" => "alexandria/devise/passwords#update"
      get "/admin_users/password/new" => "alexandria/devise/passwords#new"
      post "/admin_users/password" => "alexandria/devise/passwords#create"
    end

    # Users
    devise_for :users, controllers: { sessions: 'sessions',
                                      registrations: 'registrations',
                                      passwords: 'passwords',
                                      confirmations: 'confirmations',
                                      unlocks: 'unlocks' }
    devise_scope :user do
      get 'login' => 'sessions#new', as: :new_user_session
      post 'login' => 'sessions#create', as: :user_session
      get 'logout' => 'sessions#destroy', as: :destroy_user_session
      get 'users/disable_confirmation' => 'registrations#disable_confirmation', as: :disable_confirmation
      get 'users/reinstate' => 'registrations#reinstate_confirmation', as: :reinstate_confirmation
      put 'users/reinstate' => 'registrations#send_reinstate', as: :send_reinstate
      get 'users/reinstate_account' => 'registrations#reinstate_account_edit', as: :reinstate_account
      put 'users/reinstate_account' => 'registrations#reinstate_account', as: :reinstate_account
      get 'account-settings' => 'registrations#edit', as: :account_settings
    end

    # Payment and Invoices
    get "card" => 'card#edit'
    put "card" => 'card#update'

    resources :subscriptions, only: :index
    get '/subscriptions/:community_id/edit' => 'subscriptions#edit', as: :edit_subscription
    put '/subscriptions/:community_id' => 'subscriptions#update', as: :subscription

    resources :invoices, only: [:index, :show], path: :statements

    # Documents
    get "users/accept_document/:id" => "document_acceptance#new", as: "accept_document"
    post "users/accept_document/:id" => "document_acceptance#create", as: "accept_document_create"

    # User Profiles
    resources :user_profiles, path: :profiles, only: [:show, :edit, :update] do
      member do
        get :activities
        get :announcements
        get :invites
      end
      resources :played_games, only: [:index, :show]
    end
    get "/account" => "user_profiles#account", as: "account"
    put "/account/update" => "user_profiles#update", as: "update_account"

    # Characer and PlayedGames
    resources :played_games, only: [:new, :create, :update, :destroy] do
      resource :characters, only: [:new, :create]
      collection do
        get :autocomplete
      end
    end
    resources :characters, only: [:edit, :update, :destroy]

    # Communities
    resources :communities, only: [:show, :new, :create, :destroy] do
      get 'page/:page', action: :index, on: :collection
      get 'check_name', action: :check_name, on: :collection
      member do
        get :remove_confirmation, as: "community_remove_confirmation"
      end
    end

    # Messaging
    resources :sent_messages, only: [:create]
    get 'mail/sent/autocomplete' => "sent_messages#autocomplete", as: 'sent_autocomplete'
    get 'mail/sent/:id' => "sent_messages#show", as: "sent_mail"
    get 'mail/sent' => "sent_messages#index", as: "sent_mailbox"
    get 'mail/compose' => "sent_messages#new", as: "compose_mail"
    get 'mail/compose/:id' => "sent_messages#new", as: "compose_mail_to"
    get 'mail/inbox/:id' => "messages#show", as: "mail"
    post 'mail/mark_read/:id' => "messages#mark_read", as: "mail_mark_read"
    post 'mail/mark_unread/:id' => "messages#mark_unread", as: "mail_mark_unread"
    put 'mail/:id/move/:folder_id' => "messages#move", as: "mail_move"
    put 'mail/batch_move/:folder_id' => "messages#batch_move", as: "mail_batch_move"
    put 'mail/batch_mark_read/' => "messages#batch_mark_read", as: "mail_batch_mark_read"
    put 'mail/batch_mark_unread/' => "messages#batch_mark_unread", as: "mail_batch_mark_unread"
    get 'mail/reply/:id' => "messages#reply", as: "mail_reply"
    get 'mail/reply-all/:id' => "messages#reply_all", as: "mail_reply_all"
    get 'mail/forward/:id' => "messages#forward", as: "mail_forward"
    delete 'mail/delete/:id' => "messages#destroy", as: "mail_delete"
    delete 'mail/delete' => "messages#destroy", as: "mail_delete_all"
    delete 'mail/batch_delete' => "messages#batch_destroy", as: "mail_batch_delete"
    get 'mail/inbox' => "mailbox#inbox", as: "inbox"
    get 'mail/trash' => "mailbox#trash", as: "trash"

    # Support Tickets
    resources :support_tickets, path: :support, as: :support, only: [:index, :show, :new, :create] do

app/controllers/subdomains/announcements_controller.rb
###
# Author::    DigitalAugment Inc. (mailto:info@digitalaugment.com)
# Copyright:: Copyright (c) 2011 DigitalAugment Inc.
# License::   Proprietary Closed Source
#
# This controller is handling announcements within the scope of subdomains (communities).
###
class Subdomains::AnnouncementsController < SubdomainsController
  respond_to :html
###
# Before Filters
###
  before_filter :block_unauthorized_user!
  before_filter :ensure_current_user_is_member
  before_filter :authorize_community_and_game, only: [:community, :game]
  authorize_resource except: [:community, :game]
  load_and_authorize_resource through: :current_community, only: [:new, :create, :lock, :unlock, :destroy]

###
# REST Actions
###
  # GET /announcements/
  def index
    @announcements = current_community.announcements.includes(:community).ordered.page params[:page]
  end

  # GET /announcements/:id(.:format)
  def show
    @announcement = current_community.announcements.includes(:community).find_by_id(params[:id])
    if @announcement
      authorize!(:read, @announcement)
      current_community = Community.find_by_id(params[:community_id]) if params[:community_id]
      @announcement.update_viewed(current_user.user_profile)
      @user_profiles_have_seen = @announcement.user_profiles_have_seen.order('LOWER(display_name) ASC')
      @user_profiles_have_not_seen = @announcement.user_profiles_have_not_seen.order('LOWER(display_name) ASC')
      @comments = @announcement.comments.page params[:page]
      respond_to do |format|
        format.js {
          announcement = any_announcements_to_display? ? render_to_string(partial: 'layouts/flash_message_announcement', locals: { announcement: announcements_to_display.first }) : ''
          render text: announcement, layout: nil
        }
        format.html
      end
    else
      flash[:alert] = "Announcement not found."
      redirect_to community_announcements_url
    end
  end

  # GET /announcement_spaces/:announcement_space_id/announcements/new(.:format)
  def new
    @announcement = current_community.announcements.new()
    @announcement.community_game_id = params[:game].to_i if params.has_key? 'game'
  end

  # POST /announcement_spaces/:announcement_space_id/announcements(.:format)
  def create
    @announcement.user_profile = current_user.user_profile

    if @announcement.save
      set_last_posted_as((@announcement.charater_posted? ? @announcement.character : @announcement.user_profile))
      flash[:success] = 'Announcement was successfully created.'
    end
    respond_with(@announcement)
  end

  # DELETE /announcements/:id(.:format)
  def destroy
    flash[:notice] = 'Announcement was successfully removed.' if @announcement.destroy
    respond_with(@announcement, location: announcements_path)
  end

###
# Added Actions
###

  # GET /announcements/community(.:format)
  def community
    @announcements = current_community.community_announcements.ordered
  end

  # GET /announcements/game/:id(.:format)
  def game
    @community_game = current_community.community_games.find_by_id(params[:id])
    if !!@community_game
      @announcements = @community_game.announcements.where(community_id: current_community.id).ordered
    else
      redirect_to not_found_url
    end
  end

  # POST /announcements/:id/lock(.:format)
  def lock
    @announcement.is_locked = true
    if @announcement.save
      flash[:notice] = "Announcement was successfully locked."
    else
      flash[:alert] = "Announcement was not locked, internal rails error."
    end
    redirect_to :back
    return
  end

  # POST /announcements/:id/unlock(.:format)
  def unlock
    @announcement.is_locked = false
    if @announcement.save
      flash[:notice] = "Announcement was successfully unlocked."
    else
      flash[:alert] =  "Announcement was not unlocked, internal error."
    end
    redirect_to :back
    return
  end

  # DELETE /announcements/batch_destroy/(.:format)
  def batch_destroy
    if params[:ids]
      delete_count = 0
      params[:ids].each do |id|
        if announcement = current_community.announcements.find_by_id(id[0].to_i) and can? :destroy, announcement
          delete_count += 1 if announcement.destroy
        end
      end
      if delete_count < params[:ids].size
        flash[:alert] = "#{help.pluralize(params[:ids].size - delete_count, 'announcement')} could not be located and/or removed at this time."
      else
        flash[:success] = "#{help.pluralize(delete_count, 'announcement')} removed."
      end
    end
    redirect_to announcements_url
  end

  #Before Filter
  def authorize_community_and_game
    authorize! :index, Announcement
  end

###
# Public Methods
###
  # This method returns the current game that is in scope.
  def current_game
    @announcement.community_game if @announcement and @announcement.persisted?
  end
  helper_method :current_game
end

app/controllers/subdomains/comments_controller.rb
###
# Author::    DigitalAugment Inc. (mailto:info@digitalaugment.com)
# Copyright:: Copyright (c) 2011 DigitalAugment Inc.
# License::   Proprietary Closed Source
#
# This controller is handling comments within the scope of subdomains (communities).
###
class Subdomains::CommentsController < SubdomainsController
  layout nil

###
# Before Filters
###
  prepend_before_filter :block_unauthorized_user!
  before_filter :create_comment, only: [:new, :create]
  load_and_authorize_resource except: [:new, :create]
  authorize_resource only: [:new, :create]

###
# REST Actions
###
  # GET /comments/new
  def new
    render partial: 'form', locals: { comment: @comment }
  end

  # GET /comments/1/edit
  def edit
    render partial: 'form', locals: { comment: @comment }
  end

  # POST /comments
  def create
    if @comment.save
      set_last_posted_as(@comment.charater_posted? ? @comment.character : @comment.user_profile)
      render partial: 'comment', locals: { comment: @comment }
    else
      render text: '', layout: false
    end
  end

  # PUT /comments/1
  def update
    @comment.has_been_edited = true
    @comment.update_attributes(params[:comment])
    render partial: 'comment', locals: { comment: @comment }
  end

  # DELETE /comments/1
  def destroy
    render json: @comment.destroy ? true : false
  end

###
# Added Actions
###
  # POST /comments/:id/lock(.:format)
  def lock
    @comment.is_locked = true
    render json: @comment.save ? true : false
  end

  # POST /comments/:id/unlock(.:format)
  def unlock
    @comment.is_locked = false
    if @comment.save
      render partial: 'comment', locals: { comment: @comment }
    else
      render json: false
    end
  end

###
# Protected Methods
###
protected

###
# Callback Methods
###
  ###
  # _before_filter_
  #
  # This before filter attempts to populate @comment using current user.
  ###
  def create_comment
    if params[:comment]
      @comment = Comment.new(params[:comment])
    else
      @comment = Comment.new(commentable_type: params[:commentable_type], commentable_id: params[:commentable_id])
    end
    @comment.user_profile = current_user.user_profile
    @comment.form_target = params[:form_target] if params[:form_target]
    @comment.comment_target = params[:comment_target] if params[:comment_target]
  end
end

app/controllers/subdomains/community_invites_controller_controller.rb
class Subdomains::CommunityInvitesController < ApplicationController
respond_to :html
  ###
  # Before Filters
  ###
  before_filter :block_unauthorized_user!
  load_and_authorize_resource through: :current_community

###
# REST Actions
###
  # GET /communities
  def index
  end

  # POST /communities(.:format)
  def create
  end
end

app/views/subdomains/roster_assignments/_row.haml
%tr{ class: profile_type }
  %td.cinch
    = image_tag member_profile.avatar_url(:tiny), class: 'avatar'
  %td.cinch
    - if profile_type == 'admin'
      %strong
        = link_to member_profile.name, user_profile_url(member_profile)
      %dfn Community Admin
    - else
      = link_to member_profile.name, user_profile_url(member_profile)
  %td.characters
    - cp = member_profile.community_profiles.find_by_community_id(current_community.id)
    - if cp.roster_assignments.includes(:community_game).delete_if{|ra| ra.is_pending? or (!!community_game and ra.community_game != community_game)}.size > 0
      %ul
        - cp.roster_assignments.includes(:community_game, :character).each do |ra|
          %li
            - if can? :destroy, ra
              %input{ id: "roster_assignments_#{ra.id}", name: 'ids[]', type: 'checkbox', value: ra.id }
              %label{ for: "roster_assignments_#{ra.id}" }
                = image_tag ra.character_avatar_url(:icon), class: 'avatar icon'
                = ra.character_name
            - else
              = image_tag ra.character_avatar_url(:icon), class: 'avatar icon'
              = ra.character_name
    - elsif user_signed_in? and member_profile == current_user.user_profile
      = link_to 'Add Characters', my_roster_assignments_url
    - else
      &mdash;
  %td
    %time= l member_profile.joined_community_on(current_community), format: :date_short
  %td.actions
    %div
      - community_profile = member_profile.community_profiles.where(community_id: current_community.id).first
      - if can? :destroy, community_profile
        - if community_profile.user_profile_id == current_user.user_profile_id
          =link_to 'Remove', community_profile_url(community_profile), method: :delete, confirm: 'Are you sure you want to leave this community?', meta: 'Leave Community', class: 'remove'
        - else
          =link_to 'Remove', community_profile_url(community_profile), method: :delete, confirm: 'Are you sure you want to remove member from this community?', meta: 'Remove member', class: 'remove'

app/views/subdomains/roster_assignments/_table.haml
= form_tag '' do
  %input{ name: '_method', value: '', type: 'hidden' }
  %table.roster
    %thead
      %tr
        %th
        %th= sortable 'display_name', 'Member'
        %th Characters on the Roster
        %th Joined
        %th.actions
    %tbody
      = render 'row', member_profile: current_community.admin_profile, community_game: community_game, profile_type: 'admin' unless params[:page] or not member_profiles.include?(current_community.admin_profile)
      - if member_profiles.any?
        - member_profiles.each do |member_profile|
          - next if member_profile == current_community.admin_profile
          = render 'row', member_profile: member_profile, community_game: community_game, profile_type: 'user'
    %tfoot
      %tr
        %td{ colspan: 5, class: 'batch' }
          - if can? :manage, RosterAssignment
            = button_tag 'Remove selected characters', action: batch_destroy_roster_assignments_url, method: :delete, confirm: 'Are you sure? These characters will be no longer be a part of the community.'

app/views/subdomains/roster_assignments/edit.html.haml
%h1 Editing roster_assignment

= render 'form', :roster_assignment => @roster_assignment, :avalible_characters => @avalible_characters

= link_to 'Show', @roster_assignment
\|
= link_to 'Back', roster_assignments_path

app/views/subdomains/roster_assignments/game.haml
- title "#{@community_game.smart_name} Roster | #{current_community.name}"

#breadcrumb
  %ol
    %li= link_to "Members", roster_assignments_url
    %li
      %span= "#{@community_game.smart_name} Roster"

%h1= "#{@community_game.smart_name} Roster"
= paginate @member_profiles
= render 'table', member_profiles: @member_profiles, community_game: @community_game
= paginate @member_profiles

app/views/subdomains/roster_assignments/index.haml
- title "Members | #{current_community.name}"

%h1 Membership Roster

- if can? :edit, current_community and can? :upgrade, current_community
  #submenu
    = link_to 'Upgrade Subscription', edit_subscription_url(current_community, upgrade: true), class: 'button'

= render 'communities/population', community: current_community
-#= render 'shared/searchbox', resource: @member_profiles, action: roster_assignments_url
= paginate @member_profiles
= render 'table', member_profiles: @member_profiles, community_game: nil
= paginate @member_profiles

app/views/subdomains/roster_assignments/new.haml
- content_for :footer do
  = javascript_include_tag 'roster_assignments'

%h1 My Roster Assigments
%p
  This page keeps track of which of your characters are members of
  %strong= current_community.name

- if @roster_assignments.any? or @available_characters.any?
  %table.my_roster
    %thead
      %tr
        %th.cinch
        %th My Characters
        %th.actions
    - if @roster_assignments.any?
      %tbody
        - @roster_assignments.each do |roster_assignment|
          %tr{ roster_assignment.is_pending ? { class: 'dim' } : {} }
            %td{ class: 'avatar cinch' }
              = image_tag roster_assignment.character_avatar_url(:tiny), class: 'avatar'
            %td.character
              %h3= roster_assignment.character_name
              = roster_assignment.is_pending ? 'is pending approval to ' : 'is a member of'
              = roster_assignment.community_game_smart_name
            %td.actions
              %div
                - if  can? :mine, RosterAssignment or can? :destroy, roster_assignment
                  = link_to 'Remove', roster_assignment, confirm: 'Are you sure?', method: :delete, class: 'delete', meta: "Remove #{roster_assignment.character_name} from the roster"
    %tfoot
      %tr
        %td
        %td
          - if @available_characters.any?
            = simple_form_for @roster_assignment, wrapper: false do |f|
              .select.characters
                %ul
                  - @available_characters.each do |cp|
                    %li{ 'data-game-type' => cp.game.class.to_s.downcase }
                      = radio_button_tag 'roster_assignment[character_id]', cp.id
                      = label_tag "roster_assignment_character_id_#{cp.id}", raw(image_tag(cp.avatar_url(:icon), class: 'avatar')) + "#{cp.name} — #{cp.game_name}"
              .select.games
                %ul
                  - current_community.community_games.includes(:community).each do |sg|
                    %li{ 'data-game-type' => sg.game.class.to_s.downcase }
                      = radio_button_tag 'roster_assignment[community_game_id]', sg.id
                      = label_tag "roster_assignment_community_game_id_#{sg.id}", sg.smart_name
              %button{ type: 'submit' } Add character
        %td
- else
  %p
    %strong
      - if current_community.community_games.any?
        You do not have any characters available to be added to the roster.
        %p
          = link_to 'Add Characters', user_profile_url(current_user.user_profile) + '#characters', class: 'button'
      - else
        This community does not have any community games, and thus no rosters.
        %p
          - if can? :manage, RosterAssignment
            = link_to 'Add a Game', new_community_game_url, class: 'button'

app/views/subdomains/roster_assignments/pending.haml
%h1 Pending Character Requests

- if @roster_assignments.size > 0
  = form_tag '' do
    %input{ name: '_method', value: '', type: 'hidden' }
    %table
      %thead
        %tr
          %th.check
          %th{ colspan: 2 } Pending Character
          %th
      %tbody
        - @roster_assignments.each do |roster_assignment|
          %tr
            %td.check
              = check_box_tag "ids[#{roster_assignment.id}]", true, false, id: "roster_assignment_id_#{roster_assignment.id}"
              %label{ for: "roster_assignment_id_#{roster_assignment.id}" }
            %td.cinch
              = image_tag roster_assignment.character_avatar_url(:tiny), class: 'avatar'
            %td.character
              %h3= roster_assignment.character_name
              %strong= roster_assignment.community_game_smart_name
              %p.meta
                Requested by
                = (link_to roster_assignment.user_profile_display_name, user_profile_url(roster_assignment.user_profile) + '#characters') + ', '
                who has
                %strong= pluralize roster_assignment.community_profile.approved_characters.size, 'character'
                on the roster.
            %td.actions
              %div
                - if can? :approve, roster_assignment
                  = link_to 'Approve', approve_roster_assignment_path(roster_assignment), method: :put, class: 'approve', meta: "Approve #{roster_assignment.character_name}"
                - if can? :reject, roster_assignment
                  = link_to 'Reject', reject_roster_assignment_path(roster_assignment), confirm: 'Are you sure you want to reject this character?', method: :put, class: 'reject', meta: "Reject #{roster_assignment.character_name}"
      %tfoot
        %tr
          %td{ colspan: 4, class: 'batch' }
            = button_tag 'Approve selected', action: batch_approve_roster_assignments_url, method: :put, meta: 'Approve selected characters.'
            = button_tag 'Reject selected', action: batch_reject_roster_assignments_url, method: :put, meta: 'Reject selected characters.'
- else
  %p There are no pending requests.