config/routes.rb
        resources :submissions, shallow: true, only: [:index, :destroy]
        resources :submissions, except: [:update, :edit, :destroy]
        member do
          put :publish
          put :unpublish
        end
      end
      get "/custom_forms/:id/thankyou" => 'custom_forms#thankyou', as: :custom_form_thankyou

      # Discussions
      resources :comments, except: [:index, :show] do
        member do
          post :lock
          post :unlock
        end
      end
      resources :discussion_spaces do
        resources :discussions, except: [:index], shallow: true do
          member do
            post :lock
            post :unlock
          end
        end
      end

      # Announcements
      resources :announcements, except: [:edit, :update] do
        member do
          post :lock
          post :unlock
        end
        collection do
          get :community
          get 'game/:id' => 'announcements#game', as: :game
          delete 'batch_destroy' => "announcements#batch_destroy", as: "batch_destroy"
        end
      end

      # Pages
      resources :page_spaces do
        resources :pages, shallow: true, except: [:index]
      end

      # Community Games
      resources :community_games, except: [:show] do
        collection do
          get :autocomplete
        end
      end

      # Minecraft
      get 'minecraft/whitelist' => 'minecraft#whitelist', as: 'minecraft_whitelist'

      # Events
      resources :events do
        member do
          get :invites
        end
        collection do
          get :past
        end
      end
      get '/events/:year/:month' => 'events#month_index', as: "month_events"
      get '/events/:year/week/:week' => 'events#week_index', as: "week_events"

      # Invites
      put 'invites/batch_update' => "invites#batch_update", as: "invites_batch_update"
      resources :invites, only: [:edit, :update]

      resources :community_invites, only: [:index]
      post "/community_invites/mass_create" => "community_invites#mass_create"
      get "/community_invites/autocomplete" => "community_invites#autocomplete"
    end

  end # End of "constraints(Subdomain)" block

  # Routes that use no subdomain
  defaults subdomain: false do

    # Admin Users
    devise_for :admin_users, path: ActiveAdmin.application.default_namespace,
                             controllers: {sessions: 'alexandria/devise/sessions', passwords: 'alexandria/devise/passwords'},
                             path_names: { sign_in: 'login', sign_out: "logout" }
    devise_scope :admin_user do
      get "/alexandria/login" => "alexandria/devise/sessions#new"
      post "/alexandria/login" => "alexandria/devise/sessions#create"
      get "/alexandria/logout" => "alexandria/devise/sessions#destroy"
      get "/admin_users/sign_in" => "alexandria/devise/sessions#new"
      post "/admin_users/sign_in" => "alexandria/devise/sessions#create"
      get "/admin_users/password/edit" => "alexandria/devise/passwords#edit"
      put "/admin_users/password" => "alexandria/devise/passwords#update"
      get "/admin_users/password/new" => "alexandria/devise/passwords#new"
      post "/admin_users/password" => "alexandria/devise/passwords#create"
    end

    # Users
    devise_for :users, controllers: { sessions: 'sessions',
                                      registrations: 'registrations',
                                      passwords: 'passwords',
                                      confirmations: 'confirmations',
                                      unlocks: 'unlocks' }
    devise_scope :user do
      get 'login' => 'sessions#new', as: :new_user_session
      post 'login' => 'sessions#create', as: :user_session
      get 'logout' => 'sessions#destroy', as: :destroy_user_session
      get 'users/disable_confirmation' => 'registrations#disable_confirmation', as: :disable_confirmation
      get 'users/reinstate' => 'registrations#reinstate_confirmation', as: :reinstate_confirmation
      put 'users/reinstate' => 'registrations#send_reinstate', as: :send_reinstate
      get 'users/reinstate_account' => 'registrations#reinstate_account_edit', as: :reinstate_account
      put 'users/reinstate_account' => 'registrations#reinstate_account', as: :reinstate_account
      get 'account-settings' => 'registrations#edit', as: :account_settings
    end

    # Payment and Invoices
    get "card" => 'card#edit'
    put "card" => 'card#update'

    resources :subscriptions, only: :index
    get '/subscriptions/:community_id/edit' => 'subscriptions#edit', as: :edit_subscription
    put '/subscriptions/:community_id' => 'subscriptions#update', as: :subscription

    resources :invoices, only: [:index, :show], path: :statements

    # Documents
    get "users/accept_document/:id" => "document_acceptance#new", as: "accept_document"
    post "users/accept_document/:id" => "document_acceptance#create", as: "accept_document_create"

    # User Profiles
    resources :user_profiles, path: :profiles, only: [:show, :edit, :update] do
      member do
        get :activities
        get :announcements
        get :invites
      end
      resources :played_games, only: [:index, :show]
    end
    get "/account" => "user_profiles#account", as: "account"
    put "/account/update" => "user_profiles#update", as: "update_account"

    # Characer and PlayedGames
    resources :played_games, only: [:new, :create, :update, :destroy] do
      resource :characters, only: [:new, :create]
      collection do
        get :autocomplete
      end
    end
    resources :characters, only: [:edit, :update, :destroy]

    # Communities
    resources :communities, only: [:show, :new, :create, :destroy] do
      get 'page/:page', action: :index, on: :collection
      get 'check_name', action: :check_name, on: :collection
      member do
        get :remove_confirmation, as: "community_remove_confirmation"
      end
    end

    # Messaging
    resources :sent_messages, only: [:create]
    get 'mail/sent/autocomplete' => "sent_messages#autocomplete", as: 'sent_autocomplete'
    get 'mail/sent/:id' => "sent_messages#show", as: "sent_mail"
    get 'mail/sent' => "sent_messages#index", as: "sent_mailbox"
    get 'mail/compose' => "sent_messages#new", as: "compose_mail"
    get 'mail/compose/:id' => "sent_messages#new", as: "compose_mail_to"
    get 'mail/inbox/:id' => "messages#show", as: "mail"
    post 'mail/mark_read/:id' => "messages#mark_read", as: "mail_mark_read"
    post 'mail/mark_unread/:id' => "messages#mark_unread", as: "mail_mark_unread"
    put 'mail/:id/move/:folder_id' => "messages#move", as: "mail_move"
    put 'mail/batch_move/:folder_id' => "messages#batch_move", as: "mail_batch_move"
    put 'mail/batch_mark_read/' => "messages#batch_mark_read", as: "mail_batch_mark_read"
    put 'mail/batch_mark_unread/' => "messages#batch_mark_unread", as: "mail_batch_mark_unread"
    get 'mail/reply/:id' => "messages#reply", as: "mail_reply"
    get 'mail/reply-all/:id' => "messages#reply_all", as: "mail_reply_all"
    get 'mail/forward/:id' => "messages#forward", as: "mail_forward"
    delete 'mail/delete/:id' => "messages#destroy", as: "mail_delete"
    delete 'mail/delete' => "messages#destroy", as: "mail_delete_all"
    delete 'mail/batch_delete' => "messages#batch_destroy", as: "mail_batch_delete"
    get 'mail/inbox' => "mailbox#inbox", as: "inbox"
    get 'mail/trash' => "mailbox#trash", as: "trash"

    # Support Tickets
    resources :support_tickets, path: :support, as: :support, only: [:index, :show, :new, :create] do
      resources :support_comments, path: :comment, as: :comment, only: [:new, :create]
    end
    put 'support/:id/status/:status' => 'support_tickets#status', as: :support_status

    # CommuntiyInvites
    resources :community_invites, only: [:create]

    # Invites
    resources :invites, only: [:show]
    put 'invites/batch_update' => "invites#batch_update", as: "invites_batch_update"

    # Artwork Upload
    resources :artwork_uploads, only: [:create, :new]

    # Announcements
    resources :announcements, only: [:show]
    put 'announcements/batch_mark_as_seen' => "announcements#batch_mark_as_seen", as: "announcements_batch_mark_as_seen"

    # Site Actions
    match "/toggle_maintenance_mode" => "site_configuration#toggle_maintenance_mode", as: :toggle_maintenance_mode

    # Top level home page
    root to: 'top_level#index'
    get "top_level/index"
    get "/bar" => "top_level#bar", as: "bar"

    # Top level pages
    get "/features" => "top_level#features", as: 'top_level_features'
    get "/pricing" => "top_level#pricing", as: 'top_level_pricing'
    get "/maintenance" => "top_level#maintenance", as: 'top_level_maintenance'
    get "/privacy-policy" => "top_level#privacy_policy", as: 'top_level_privacy_policy'
    get "/terms-of-service" => "top_level#terms_of_service", as: 'top_level_terms_of_service'
    get "/trademark-disclaimer" => "top_level#trademark_disclaimer", as: 'top_level_trademark_disclaimer'
    match "/ignore_browser" => "top_level#ignore_browser", as: 'ignore_browser'
    get "/search" => "search#index", as: 'search'
    get "/search/autocomplete" => "search#autocomplete", as: 'search_autocomplete'

    get '/robots.txt' => 'status_code#robots'

  ###
  # Verification Codes
  ###
    get '/mu-2656c9d8-02082dc2-3904fc4c-9012184b' => "status_code#blitz"
    get '/loaderio-5990c4bd3e6704d1a506c842975428c3' => "status_code#loaderio"

    # Error Handling and Testing
    get 'bang' => 'status_code#bang' # Test errors

    get "/unsupported_browser" => "status_code#unsupported_browser", as: 'unsupported_browser'
    match '/not_found' => 'status_code#not_found', as: 'not_found'
    match '/forbidden' => 'status_code#forbidden', as: 'forbidden'
    match '/internal_server_error' => 'status_code#internal_server_error', as: 'internal_server_error'

    match "/404", to: "status_code#not_found"
    match "/500", to: "status_code#internal_server_error"

app/controllers/subscriptions_controller.rb
###
# Author::    DigitalAugment Inc. (mailto:info@digitalaugment.com)
# Copyright:: Copyright (c) 2011 DigitalAugment Inc.
# License::   Proprietary Closed Source
#
# Controller used to manage community subscriptions.
###
class SubscriptionsController < PaymentController
  respond_to :html, :js

###
# Callbacks
###
  before_filter :load_variables
  before_filter :load_community, only: [:edit, :update]

  # GET /subscriptions(.:format)
  def index
    @owned_communities = current_user.owned_communities
  end

  # GET /subscriptions/:community_id/edit(.:format)
  def edit
    # Get invoice item for current plan.
    @current_plan_invoice_item = @invoice.plan_invoice_item_for_community(@community)

    # Get all upgrades for the current community.
    @all_upgrades_invoice_items = @invoice.recurring_upgrade_invoice_items_for_community(@community)

    # TODO: After Adding more CommunityUpgrades - This should check that there exists a upgrade for all available upgrades for the current plan.
    if @all_upgrades_invoice_items.blank?
      # TODO: After Adding more CommunityUpgrades - For each missing upgrade add a zero quantity one (so the user can add upgrades).
      @all_upgrades_invoice_items = @invoice.invoice_items.new({item: CommunityUpgrade.first, quantity: 0, community_id: @community.id}, without_protection: true)
    end

    flash[:success] = "To upgrade to a Pro community, add or update your card on file click 'Update Subscription'." if params[:upgrade] == 'true'
    flash[:notice] = "Your #{@community.current_community_plan.title} subscription will be active until #{@invoice.period_end_date.strftime('%B %d, %Y')}." if @invoice.is_downgrading?(@community)
  end

  # PUT /subscriptions/:community_id
  def update
    @stripe_card_token = params[:stripe_card_token]
    begin
      success_message = "Your plan has been changed"
      success = false
      # Check to see if the community is charge exempt..
      if @community.is_charge_exempt
        #.. If it is just update it.
        success = @invoice.update_attributes(params[:invoice])
        flash.now[:error] = "We were unable to update your account at this time." unless success
      else
        #.. If it is not exempt, try to update it with payment..
        success = @invoice.update_attributes_with_payment(params[:invoice], @stripe_card_token)
      end
    # Rescue from Stripe errors and let the user know what is happening.
    rescue Stripe::StripeError => e
      @invoice.errors.add :base, "There was a problem with your credit card"
      @stripe_card_token = nil
    # Rescue from stale objects (Locked) and let the user know what is happening.
    rescue ActiveRecord::StaleObjectError => e
      # ERROR invoice is currently being charged.
      flash.now[:alert] = "Your invoice is currently being charged."
      redirect_to subscriptions_path
      return true
    end

    if success
      flash.now[:success] = success_message
    else
      #.. If it can't be updated with payment, then set the view variables from the current invoice.
      @current_plan_invoice_item = @invoice.invoice_items.select{|ii| ii.has_community_plan?}.first
      @all_upgrades_invoice_items = @invoice.invoice_items.recurring.select{|ii| ii.has_community_upgrade?}
    end

    respond_with(@invoice, location: edit_subscription_url(@community))
  end

###
# Protected Methods
###
protected

  ###
  # _before_filter_
  #
  # Loads variables
  ###
  def load_variables
    @available_plans = CommunityPlan.available
    @invoice = current_user.current_invoice
  end

  ###
  # _before_filter_
  #
  # Loads community used by edit and update.
  ###
  def load_community
    @community = current_user.owned_communities.find(params[:community_id])
    begin
      @stripe = Stripe::Customer.retrieve(current_user.stripe_customer_token) unless current_user.stripe_customer_token.blank?
    rescue
    ensure
      @stripe ||= nil
    end
    if @invoice.processing_payment
      flash[:notice] = "Your account is currently being processd and no changes can be made at this time."
      redirect_to subscriptions_url
    end
  end
end

app/views/subscriptions/_notice.haml
%blockquote
  %p
    %strong Note:
    Our automated billing system will charge your account every 30 days in advance for your subscription(s).

app/views/subscriptions/edit.haml
- title 'Edit Subscription'

- card_on_file = !!@stripe
- card_is_present = (@stripe_card_token.present? or current_user.stripe_customer_token.present?)

- content_for :header do
  %meta{ name: "stripe-key", content: STRIPE_PUBLIC_KEY }
  = stylesheet_link_tag "top_level/subscriptions"

- content_for :footer do
  %script{ type: 'text/javascript' }
    :plain
      var requireConfirmation = #{(@invoice.persisted? or @invoice.period_end_date < Time.now) ? 'false' : 'true'};
  = javascript_include_tag "https://js.stripe.com/v1/"
  = javascript_include_tag "subscriptions"

%h1= shorten_words @community.name

= render 'shared/subscriptions_submenu'

= simple_form_for @invoice, url: subscription_url(@community), method: :put, html: {novalidate: true, id: "form_with_subscription"} do |f|
  %fieldset
    = hidden_field_tag :stripe_card_token
    %ol
      %li.plans
        = f.simple_fields_for :invoice_items, @current_plan_invoice_item do |sf|
          = sf.input :community_id, as: :hidden
          = sf.input :item_type, as: :hidden
          = sf.input :quantity, as: :hidden

        - @available_plans.each do |plan|
          - is_current = ((params[:upgrade] == 'true' and !plan.is_free_plan?) or (params[:upgrade] != 'true' and plan.id == @current_plan_invoice_item.item_id))
          %input{ id: "community_plan_#{plan.id}", type: 'radio', name: 'invoice[invoice_items_attributes][0][item_id]', data: {price: plan.price_per_month_in_cents, members: plan.max_number_of_users}, value: plan.id, checked: is_current ? 'checked' : nil }
          %label{ for: "community_plan_#{plan.id}", title: plan.description }
            %span.title= plan.title.gsub(/\s*community\s*/i, '')
            %span.price
              - if plan.price_per_month_in_cents > 0
                = "#{number_to_currency(plan.price_per_month_in_dollars)}/month"
              - else
                This one is on us
            %span.meta
              - if plan.price_per_month_in_cents > 0
                = "#{plan.max_number_of_users} members + custom roles"
              - else
                = "Up to #{plan.max_number_of_users} members"

    = render "communities/population", community: @community

    #upgrades.section
      %h1 Add Members
      %p
        Need room for more than 100 members?
        %br
        Let Tabard grow with you by adding additional member packs.
      %ol
        = f.simple_fields_for :invoice_items, @all_upgrades_invoice_items do |sf|
          = sf.input :community_id, as: :hidden
          = sf.input :item_type, as: :hidden
          = sf.input :item_id, as: :hidden
          - collection = (1..sf.object.item.max_number_of_upgrades).collect {|u| ["+#{number_with_delimiter(u * sf.object.item.number_of_bonus_users)} members — #{number_to_currency(u * sf.object.price_per_month_in_dollars, precision: 0)}/mo", u]}
          - collection.unshift(['None',0])
          - data = sf.object.persisted? ? {destroy: 'upgrade_pack'} : {}
          = sf.input :quantity, as: :radio_buttons, collection: collection, include_blank: false, label: false, wrapper_html: {class: 'select members_package', data: data}
          = sf.input :_destroy, as: :hidden, default: true, input_html: {data: data}

    - if @community.is_charge_exempt
      %blockquote#charge_exempt
        %h1 Discount
        = @community.charge_exempt_label
        %p
          %strong Regular Price:
          %strike= number_to_currency(@invoice.non_exempt_total_recurring_price_per_month_in_dollars(@community))
          %br
          %strong Discounted Price:
          = number_to_currency(@invoice.total_recurring_price_per_month_in_dollars(@community))

    - else
      #cc_input.section{ class: card_is_present ? '' : 'show_fields' }
        %h1 Payment

        - if card_is_present
          = render 'card/current', stripe: @stripe if card_on_file
          %menu
            = link_to 'Change card', 'javascript:;', class: 'newcard'
            = link_to 'Use card on file', 'javascript:;', class: 'onfile'

        %fieldset{ id: 'cc_fields', class: card_is_present ? 'hide' : '' }
          = render 'card/accepted'
          %ol= render 'card/fields'
          = render "subscriptions/notice"

    %p.submit
      = f.button :submit, 'Update Subscription'

app/views/subscriptions/index.haml
- title 'Subscriptions'

%h1 Subscriptions

= render 'shared/subscriptions_submenu', current: 'subscriptions'

- if @owned_communities.size > 0
  - if current_user.total_recurring_price_per_month_in_dollars > 0
    = render "subscriptions/notice"
  %table
    %thead
      %tr
        %th Community
        %th Subscription
        %th.r Cost
        %th
    %tbody
      - @owned_communities.each do |community|
        - recurring = @invoice.plan_invoice_item_for_community(community)
        %tr
          %td
            %h3= link_to shorten_words(community.name, 21), edit_subscription_path(community)
            - if community.is_charge_exempt
              %p
                %strong Discount:
                = community.charge_exempt_label
          %td.nowrap
            - if recurring.persisted? and community.current_community_plan_title != community.recurring_community_plan_title
              %strike= community.current_community_plan_title
              %br
              %strong= community.recurring_community_plan_title
              %time
                = recurring.start_date.strftime '%b %e, %Y'
                &mdash;
                = recurring.end_date.strftime '%b %e, %Y'
            - else
              %strong= community.current_community_plan_title
          %td.r
            - if community.is_charge_exempt
              %strike= number_to_currency(@invoice.non_exempt_total_recurring_price_per_month_in_dollars(community))
              %br
            %strong= number_to_currency(@invoice.total_recurring_price_per_month_in_dollars(community))
          %td.actions
            %div
              - if recurring.persisted?
                = link_to 'Edit', edit_subscription_path(community), class: 'edit', meta: 'Edit subscription'
              - else
                = link_to 'Upgrade', edit_subscription_url(community, upgrade: true), class: 'upgrade', meta: 'Upgrade to pro'
    %tfoot
      %tr
        %td.r{ colspan: 2 }
          = "Subscription#{@owned_communities.size > 1 ? 's' : ''} Subtotal:"
          %br
          Next scheduled payment (#{@invoice.period_start_date.strftime("%b %e, %Y")}):
        %td.r
          = number_to_currency(current_user.total_recurring_price_per_month_in_dollars)
          %br
          = number_to_currency(current_user.current_invoice.total_price_in_dollars)
          - if !@invoice.is_closed? and @invoice.tax_error_occurred
            (Tax&nbsp;is&nbsp;estimated)
        %td

  %p.r
    = link_to 'View Statement', current_user.invoices.last, meta: 'Current statement', class: 'button'

- else
  %p You don't have any active subscriptions.