config/routes.rb
        resources :submissions, shallow: true, only: [:index, :destroy]
        resources :submissions, except: [:update, :edit, :destroy]
        member do
          put :publish
          put :unpublish
        end
      end
      get "/custom_forms/:id/thankyou" => 'custom_forms#thankyou', as: :custom_form_thankyou

      # Discussions
      resources :comments, except: [:index, :show] do
        member do
          post :lock
          post :unlock
        end
      end
      resources :discussion_spaces do
        resources :discussions, except: [:index], shallow: true do
          member do
            post :lock
            post :unlock
          end
        end
      end

      # Announcements
      resources :announcements, except: [:edit, :update] do
        member do
          post :lock
          post :unlock
        end
        collection do
          get :community
          get 'game/:id' => 'announcements#game', as: :game
          delete 'batch_destroy' => "announcements#batch_destroy", as: "batch_destroy"
        end
      end

      # Pages
      resources :page_spaces do
        resources :pages, shallow: true, except: [:index]
      end

      # Community Games
      resources :community_games, except: [:show] do
        collection do
          get :autocomplete
        end
      end

      # Minecraft
      get 'minecraft/whitelist' => 'minecraft#whitelist', as: 'minecraft_whitelist'

      # Events
      resources :events do
        member do
          get :invites
        end
        collection do
          get :past
        end
      end
      get '/events/:year/:month' => 'events#month_index', as: "month_events"
      get '/events/:year/week/:week' => 'events#week_index', as: "week_events"

      # Invites
      put 'invites/batch_update' => "invites#batch_update", as: "invites_batch_update"
      resources :invites, only: [:edit, :update]

      resources :community_invites, only: [:index]
      post "/community_invites/mass_create" => "community_invites#mass_create"
      get "/community_invites/autocomplete" => "community_invites#autocomplete"
    end

  end # End of "constraints(Subdomain)" block

  # Routes that use no subdomain
  defaults subdomain: false do

    # Admin Users
    devise_for :admin_users, path: ActiveAdmin.application.default_namespace,
                             controllers: {sessions: 'alexandria/devise/sessions', passwords: 'alexandria/devise/passwords'},
                             path_names: { sign_in: 'login', sign_out: "logout" }
    devise_scope :admin_user do
      get "/alexandria/login" => "alexandria/devise/sessions#new"
      post "/alexandria/login" => "alexandria/devise/sessions#create"
      get "/alexandria/logout" => "alexandria/devise/sessions#destroy"
      get "/admin_users/sign_in" => "alexandria/devise/sessions#new"
      post "/admin_users/sign_in" => "alexandria/devise/sessions#create"
      get "/admin_users/password/edit" => "alexandria/devise/passwords#edit"
      put "/admin_users/password" => "alexandria/devise/passwords#update"
      get "/admin_users/password/new" => "alexandria/devise/passwords#new"
      post "/admin_users/password" => "alexandria/devise/passwords#create"
    end

    # Users
    devise_for :users, controllers: { sessions: 'sessions',
                                      registrations: 'registrations',
                                      passwords: 'passwords',
                                      confirmations: 'confirmations',
                                      unlocks: 'unlocks' }
    devise_scope :user do
      get 'login' => 'sessions#new', as: :new_user_session
      post 'login' => 'sessions#create', as: :user_session
      get 'logout' => 'sessions#destroy', as: :destroy_user_session
      get 'users/disable_confirmation' => 'registrations#disable_confirmation', as: :disable_confirmation
      get 'users/reinstate' => 'registrations#reinstate_confirmation', as: :reinstate_confirmation
      put 'users/reinstate' => 'registrations#send_reinstate', as: :send_reinstate
      get 'users/reinstate_account' => 'registrations#reinstate_account_edit', as: :reinstate_account
      put 'users/reinstate_account' => 'registrations#reinstate_account', as: :reinstate_account
      get 'account-settings' => 'registrations#edit', as: :account_settings
    end

    # Payment and Invoices
    get "card" => 'card#edit'
    put "card" => 'card#update'

    resources :subscriptions, only: :index
    get '/subscriptions/:community_id/edit' => 'subscriptions#edit', as: :edit_subscription
    put '/subscriptions/:community_id' => 'subscriptions#update', as: :subscription

    resources :invoices, only: [:index, :show], path: :statements

    # Documents
    get "users/accept_document/:id" => "document_acceptance#new", as: "accept_document"
    post "users/accept_document/:id" => "document_acceptance#create", as: "accept_document_create"

    # User Profiles
    resources :user_profiles, path: :profiles, only: [:show, :edit, :update] do
      member do
        get :activities
        get :announcements
        get :invites
      end
      resources :played_games, only: [:index, :show]
    end
    get "/account" => "user_profiles#account", as: "account"
    put "/account/update" => "user_profiles#update", as: "update_account"

    # Characer and PlayedGames
    resources :played_games, only: [:new, :create, :update, :destroy] do
      resource :characters, only: [:new, :create]
      collection do
        get :autocomplete
      end
    end
    resources :characters, only: [:edit, :update, :destroy]

    # Communities
    resources :communities, only: [:show, :new, :create, :destroy] do
      get 'page/:page', action: :index, on: :collection
      get 'check_name', action: :check_name, on: :collection
      member do
        get :remove_confirmation, as: "community_remove_confirmation"
      end
    end

    # Messaging
    resources :sent_messages, only: [:create]
    get 'mail/sent/autocomplete' => "sent_messages#autocomplete", as: 'sent_autocomplete'
    get 'mail/sent/:id' => "sent_messages#show", as: "sent_mail"
    get 'mail/sent' => "sent_messages#index", as: "sent_mailbox"
    get 'mail/compose' => "sent_messages#new", as: "compose_mail"
    get 'mail/compose/:id' => "sent_messages#new", as: "compose_mail_to"
    get 'mail/inbox/:id' => "messages#show", as: "mail"
    post 'mail/mark_read/:id' => "messages#mark_read", as: "mail_mark_read"
    post 'mail/mark_unread/:id' => "messages#mark_unread", as: "mail_mark_unread"
    put 'mail/:id/move/:folder_id' => "messages#move", as: "mail_move"
    put 'mail/batch_move/:folder_id' => "messages#batch_move", as: "mail_batch_move"
    put 'mail/batch_mark_read/' => "messages#batch_mark_read", as: "mail_batch_mark_read"
    put 'mail/batch_mark_unread/' => "messages#batch_mark_unread", as: "mail_batch_mark_unread"
    get 'mail/reply/:id' => "messages#reply", as: "mail_reply"
    get 'mail/reply-all/:id' => "messages#reply_all", as: "mail_reply_all"
    get 'mail/forward/:id' => "messages#forward", as: "mail_forward"
    delete 'mail/delete/:id' => "messages#destroy", as: "mail_delete"
    delete 'mail/delete' => "messages#destroy", as: "mail_delete_all"
    delete 'mail/batch_delete' => "messages#batch_destroy", as: "mail_batch_delete"
    get 'mail/inbox' => "mailbox#inbox", as: "inbox"
    get 'mail/trash' => "mailbox#trash", as: "trash"

    # Support Tickets
    resources :support_tickets, path: :support, as: :support, only: [:index, :show, :new, :create] do
      resources :support_comments, path: :comment, as: :comment, only: [:new, :create]
    end
    put 'support/:id/status/:status' => 'support_tickets#status', as: :support_status

    # CommuntiyInvites
    resources :community_invites, only: [:create]

    # Invites
    resources :invites, only: [:show]
    put 'invites/batch_update' => "invites#batch_update", as: "invites_batch_update"

    # Artwork Upload
    resources :artwork_uploads, only: [:create, :new]

    # Announcements
    resources :announcements, only: [:show]
    put 'announcements/batch_mark_as_seen' => "announcements#batch_mark_as_seen", as: "announcements_batch_mark_as_seen"

    # Site Actions
    match "/toggle_maintenance_mode" => "site_configuration#toggle_maintenance_mode", as: :toggle_maintenance_mode

    # Top level home page
    root to: 'top_level#index'
    get "top_level/index"
    get "/bar" => "top_level#bar", as: "bar"

    # Top level pages
    get "/features" => "top_level#features", as: 'top_level_features'
    get "/pricing" => "top_level#pricing", as: 'top_level_pricing'
    get "/maintenance" => "top_level#maintenance", as: 'top_level_maintenance'
    get "/privacy-policy" => "top_level#privacy_policy", as: 'top_level_privacy_policy'
    get "/terms-of-service" => "top_level#terms_of_service", as: 'top_level_terms_of_service'
    get "/trademark-disclaimer" => "top_level#trademark_disclaimer", as: 'top_level_trademark_disclaimer'
    match "/ignore_browser" => "top_level#ignore_browser", as: 'ignore_browser'
    get "/search" => "search#index", as: 'search'
    get "/search/autocomplete" => "search#autocomplete", as: 'search_autocomplete'

    get '/robots.txt' => 'status_code#robots'

  ###
  # Verification Codes
  ###
    get '/mu-2656c9d8-02082dc2-3904fc4c-9012184b' => "status_code#blitz"
    get '/loaderio-5990c4bd3e6704d1a506c842975428c3' => "status_code#loaderio"

    # Error Handling and Testing
    get 'bang' => 'status_code#bang' # Test errors

    get "/unsupported_browser" => "status_code#unsupported_browser", as: 'unsupported_browser'
    match '/not_found' => 'status_code#not_found', as: 'not_found'
    match '/forbidden' => 'status_code#forbidden', as: 'forbidden'
    match '/internal_server_error' => 'status_code#internal_server_error', as: 'internal_server_error'

    match "/404", to: "status_code#not_found"
    match "/500", to: "status_code#internal_server_error"

app/controllers/card_controller.rb
###
# Author::    DigitalAugment Inc. (mailto:info@digitalaugment.com)
# Copyright:: Copyright (c) 2011 DigitalAugment Inc.
# License::   Proprietary Closed Source
#
# Controller used to edit card information
###
class CardController < PaymentController
  respond_to :html, :js

  # GET /card
  def edit
    begin
      @stripe = Stripe::Customer.retrieve(current_user.stripe_customer_token) unless current_user.stripe_customer_token.blank?
    rescue
    ensure
      @stripe ||= nil
    end
    @invoice = current_user.current_invoice
    # Set invoice to nil if the invoice is not delinquent.
    @invoice = nil unless @invoice.persisted? and (@invoice.period_end_date < Time.now and @invoice.total_price_in_cents > 0)
  end

  # PUT /card
  def update
    @stripe_card_token = params[:stripe_card_token]
    begin
      if current_user.update_stripe(@stripe_card_token)
        flash.now[:success] = "Your card has been updated"
        @invoice = current_user.current_invoice
        if @invoice.persisted? and @invoice.period_end_date < Time.now and @invoice.total_price_in_cents > 0
          @invoice.charge_customer(false)
        else
          @invoice = nil
        end
      else
        self.errors.add :base, "There was a problem with your credit card. Insure your full billing address is provided."
      end
    rescue Stripe::StripeError => e
      flash.now[:error] = "#{e.message}"
      @stripe_card_token = nil
    rescue ActiveRecord::StaleObjectError => e
      # ERROR invoice is currently being charged.
      flash.now[:alert] = "Your invoice is currently being charged."
    end
    begin
      @stripe = Stripe::Customer.retrieve(current_user.stripe_customer_token) unless current_user.stripe_customer_token.blank?
    rescue
    ensure
      @stripe ||= nil
    end
    render :edit
  end
end

app/views/card/_accepted.haml
.acceptedcards
  %h2 Accepted Cards
  %ul
    %li
      = image_tag 'application/card-visa@48.png'
      Visa
    %li
      = image_tag 'application/card-mastercard@48.png'
      MasterCard
    %li
      = image_tag 'application/card-americanexpress@48.png'
      American Express
    %li
      = image_tag 'application/card-discover@48.png'
      Discover
    %li
      = image_tag 'application/card-jcb@48.png'
      JCB
    %li
      = image_tag 'application/card-dinersclub@48.png'
      Diners Club

app/views/card/_current.haml
%blockquote.card-on-file
  %p
    = image_tag "application/card-#{stripe.active_card.type.gsub(/[^a-z]/i,'').downcase}@48.png"
    - nice_date = DateTime.new(stripe.active_card.exp_year, stripe.active_card.exp_month).strftime '%B, %Y'
    %strong= "#{stripe.active_card.type} ending in #{stripe.active_card.last4}, expiring #{nice_date}"

app/views/card/_fields.haml
%li
  = label_tag :card_name, "Name on Card "
  = text_field_tag :card_name, nil, name: nil

%li
  = label_tag :card_number, "Card Number "
  = text_field_tag :card_number, nil, name: nil

%li.selects
  %label Card Expiration
  .select{ id: 'card_exp_month', class: 'month', data: {placeholder: 'Month'} }
    %ul
      - (1..12).each do |m|
        %li
          %input{ type: 'radio', name: 'card_month', id: "card_exp_month_#{m}", value: m }
          %label{ for: "card_exp_month_#{m}" }= Date::MONTHNAMES[m]
  .select{ id: 'card_exp_year', class: 'year', data: {placeholder: 'Year'} }
    %ul
      - (Date.today.year .. Date.today.year+15).each do |y|
        %li
          %input{ type: 'radio', name: 'card_year', id: "card_exp_year_#{y}", value: y }
          %label{ for: "card_exp_year_#{y}" }= y

%li
  = label_tag :card_cvc, "Security Code"
  = text_field_tag :card_cvc, nil, name: nil, style: 'width: 100px'
  %dfn.hint 3 or 4 digit number on the back of your card

%li
  = label_tag :card_address, "Billing Address"
  = text_field_tag :card_address, nil, name: nil

%li
  = label_tag :card_city, "City"
  = text_field_tag :card_city, nil, name: nil

%li
  = label_tag :card_zip, "State / Zip"

  .select{ data: {placeholder: 'State'}, style: 'float: left; margin-right: 22px; width: 200px' }
    %ul
      - us_states.each do |state|
        %li
          = radio_button_tag "card_state", state[1], false
          = label_tag "card_state_#{state[1]}", state[0]

  = text_field_tag :card_zip, nil, name: nil, style: 'float: left; width: 150px', placeholder: 'Zip/Postal Code'

  %br

app/views/card/edit.haml
- card_on_file = !!@stripe
- title = "#{card_on_file ? 'Update' : 'Add'} Card"
- title title

- content_for :header do
  %meta{ name: "stripe-key", content: STRIPE_PUBLIC_KEY }
  = stylesheet_link_tag "top_level/subscriptions"

- content_for :footer do
  %script{ type: 'text/javascript' }
    :plain
      var requireConfirmation = #{!!@invoice ? 'true' : 'false'};
  = javascript_include_tag "https://js.stripe.com/v1/"
  = javascript_include_tag "card"

- if card_on_file
  %h1 Card on File
  = render 'current', stripe: @stripe

= render 'shared/subscriptions_submenu', current: 'card'

= form_tag card_url, method: :put, id: 'card_form' do
  = hidden_field_tag 'stripe_card_token'
  %fieldset
    %h1= title
    = render 'card/accepted'
    %ol= render 'card/fields'
    - if !!@invoice
      %hr
      %h2
        = number_to_currency(@invoice.total_price_in_dollars)
        Outstanding Balance
      = link_to 'View Statement', current_user.invoices.last, target: '_blank'
      &mdash;
      %time
        From
        = @invoice.period_start_date.strftime '%b %e, %Y'
    %p.submit
      = submit_tag 'Submit', class: 'button'